# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

title: Trusted-CPP Documentation
email: 
description: >-
  Safe software development for C++
  Безопасная разработка программ на C++
baseurl: ""
url: "https://trusted-cpp.org"

# Build settings
markdown: kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM
  syntax_highlighter: rouge
  # do not replace newlines by <br>s
  hard_wrap: false

highlighter: rouge
syntax_highlighter: rouge

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for multilingual documentation
collections:
  russian_docs:
    output: true
    permalink: /ru/:path/

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Language settings
languages:
  - en
  - ru

defaults:
  - scope:
      path: ""
    values:
      lang: "en"
  - scope:
      path: "ru"
    values:
      lang: "ru"
